{% set version = "3.2.4" %}

package:
  name: bison
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/bison/bison-{{ version }}.tar.gz
  # sha256: a7cb36b55316eeec626865c03d2a44210617a17c7d393ee63d8553e0649ee946  # 3.1
  sha256: cb673e2298d34b5e46ba7df0641afa734da1457ce47de491863407a587eec79a  # 3.2.4

build:
  skip: true  # [win]
  number: 1000
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m4
    - perl
    - make
  host:
    - flex

test:
  commands:
    - yacc --help   # [unix]
    - bison --help  # [unix]

about:
  home: https://www.gnu.org/software/bison/
  license: GPL 3
  license_file: COPYING
  summary: General purpose parser generator converting annotated context-free grammar to a deterministic LR/GLR parser.
  description: |
    Bison is a general-purpose parser generator that converts an annotated
    context-free grammar into a deterministic LR or generalized LR (GLR) parser
    employing LALR(1) parser tables.
  dev_url: https://git.savannah.gnu.org/git/bison.git
  doc_url: http://savannah.gnu.org/projects/bison/

extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
